name: ci
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

env:
  PIP_CACHE_DIR: ~/.cache/pip
  cache_id: ${{ github.run_id }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Update pip & install build tools
        run: python -m pip install --upgrade pip build wheel

      # - name: Install project (editable) and dev deps
      #   run: |
      #     # If you have extras: pip install -e ".[dev]" or pip install -r requirements.txt
      #     python -m pip install -e .
      #     python -m pip install -r requirements.txt || true
      #     # optionally install dev tools
      #     python -m pip install ruff mypy pytest mkdocs mkdocs-material mkdocs-marimo || true

      # - name: Lint (ruff)
      #   run: ruff check .

      # - name: Typecheck (mypy)
      #   run: mypy .

      # - name: Tests (pytest)
      #   run: pytest -q

  deploy-docs:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: mkdocs-material-${{ env.cache_id }}
          restore-keys: |
            mkdocs-material-

      - name: Install docs dependencies and project
        run: |
          # python -m pip install --upgrade pip
          # python -m pip install -e .
          python -m pip install mkdocs-material mkdocs-marimo

      - name: Build and deploy docs
        run: mkdocs gh-deploy --force
